# Generated by Django 5.2.12 on 2026-04-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='redeemed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
