# Generated by Django 5.2.12 on 2026-04-20 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=64)),
                ('lastPlayedTime', models.DateTimeField(blank=True, null=True)),
                ('hasPlayed', models.BooleanField(blank=True, null=True)),
                ('victory', models.BooleanField(blank=True, null=True)),
                ('redeemed', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gameName')},
            },
        ),
    ]
