# Generated by Django 5.2.12 on 2026-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='timesPlayed',
            field=models.IntegerField(default=0),
        ),
    ]
