# Generated by Django 5.2.12 on 2026-04-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gameresult_timesplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpack',
            name='equipped_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equippedItem', to='main.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='timesPlayed',
            field=models.IntegerField(default=1),
        ),
    ]
